sonar.projectKey=Aryan-Jivani_Learn-Scala
sonar.organization=aryan-jivani

sonar.sources=src/main/scala
sonar.tests=src/test/scala

sonar.scala.coverage.reportPaths=target/scala-2.12/scoverage-report/scoverage.xml

sonar.sourceEncoding=UTF-8
